# Generated by Django 4.0.5 on 2022-07-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('course_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionmodel',
            name='course',
            field=models.ForeignKey(default=-1219, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesectionmodel',
            name='description',
            field=models.TextField(default='demo descriptiom'),
            preserve_default=False,
        ),
    ]
