# Generated by Django 4.0.5 on 2022-07-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursemodel_total_duration_coursemodel_total_videos'),
        ('course_section', '0003_coursesectionmodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesectionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='course.coursemodel'),
        ),
    ]
