# Generated by Django 4.0.5 on 2022-08-05 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 13, 16, 667133, tzinfo=utc)),
        ),
    ]
