# Generated by Django 4.0.5 on 2022-08-05 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_progress', '0002_studentprogressmodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogressmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
