# Generated by Django 4.0.5 on 2022-08-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_progress', '0005_remove_studentprogressmodel_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogressmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprogressmodel',
            name='student',
        ),
    ]
