# Generated by Django 4.0.5 on 2022-07-16 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_on', models.DateTimeField()),
                ('course_status', models.CharField(choices=[('approved', 'approved'), ('not-approved', 'not-approved'), ('drafted', 'drafted')], max_length=14)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
