# Generated by Django 4.0.5 on 2022-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_category_coursemodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='total_duration',
            field=models.IntegerField(default=-2012),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='total_videos',
            field=models.IntegerField(default=-2012),
            preserve_default=False,
        ),
    ]
