# Generated by Django 4.0.5 on 2022-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursemodel_total_duration_coursemodel_total_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_status',
            field=models.CharField(choices=[('published', 'published'), ('requested', 'resquested'), ('drafted', 'drafted')], max_length=14),
        ),
    ]
