# Generated by Django 4.0.5 on 2022-07-31 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursereviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollmentmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coursereviewmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
