# Generated by Django 4.0.5 on 2022-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_courseenrollmentmodel_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollmentmodel',
            name='meta',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursereviewmodel',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
