# Generated by Django 4.0.5 on 2022-08-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_courseenrollmentmodel_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereviewmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='coursereviewmodel',
            name='course',
            field=models.ManyToManyField(to='course.coursemodel'),
        ),
    ]
