# Generated by Django 4.0.5 on 2022-08-01 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_remove_coursereviewmodel_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereviewmodel',
            name='student',
        ),
        migrations.AddField(
            model_name='coursereviewmodel',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
