# Generated by Django 4.0.5 on 2022-08-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_coursereviewmodel_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollmentmodel',
            old_name='meta',
            new_name='meta_data',
        ),
    ]
