# Generated by Django 4.0.5 on 2022-08-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_meta_courseenrollmentmodel_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(default='demo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='profile_image_public_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
