# Generated by Django 4.0.5 on 2022-08-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_coursemodel_description_coursemodel_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='profile_image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='profile_image_public_id',
            new_name='cover_image_public_id',
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_status',
            field=models.CharField(choices=[('published', 'published'), ('requested', 'requested'), ('drafted', 'drafted')], default='drafted', max_length=14),
        ),
    ]
