# Generated by Django 4.0.5 on 2022-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_rename_profile_image_coursemodel_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewmodel',
            name='course',
            field=models.ManyToManyField(related_name='review', to='course.coursemodel'),
        ),
    ]
