# Generated by Django 4.0.5 on 2022-08-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_coursereviewmodel_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReviewModel',
        ),
    ]
