# Generated by Django 4.0.5 on 2022-08-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_delete_coursereviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='total_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='total_videos',
            field=models.IntegerField(null=True),
        ),
    ]
