# Generated by Django 4.0.5 on 2022-08-10 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_categorymodel_created_on'),
        ('course', '0019_alter_coursemodel_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='category.categorymodel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
