# Generated by Django 4.0.5 on 2022-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_coursemodel_category_alter_coursemodel_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='total_videos',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
