# Generated by Django 4.0.5 on 2022-08-13 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0024_remove_courseenrollmentmodel_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollmentmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='courseenrollmentmodel',
            name='course',
            field=models.ManyToManyField(to='course.coursemodel'),
        ),
        migrations.RemoveField(
            model_name='courseenrollmentmodel',
            name='student',
        ),
        migrations.AddField(
            model_name='courseenrollmentmodel',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
