# Generated by Django 4.0.5 on 2022-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_link_public_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CourseVideo',
                'verbose_name_plural': 'CourseVideos',
            },
        ),
    ]
