# Generated by Django 4.0.5 on 2022-07-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_section', '0001_initial'),
        ('course_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='description',
            field=models.TextField(default='demo description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_section.coursesectionmodel'),
        ),
    ]
