# Generated by Django 4.0.5 on 2022-07-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_section', '0001_initial'),
        ('course_video', '0002_coursevideo_description_coursevideo_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_section.coursesectionmodel'),
        ),
    ]
