# Generated by Django 4.0.5 on 2022-07-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0003_alter_coursevideo_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='duration',
            field=models.IntegerField(default=-2012),
            preserve_default=False,
        ),
    ]
