# Generated by Django 4.0.5 on 2022-07-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_section', '0004_alter_coursesectionmodel_course'),
        ('course_video', '0008_alter_coursevideomodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideomodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='course_section.coursesectionmodel'),
        ),
    ]
