# Generated by Django 4.0.5 on 2022-07-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0009_alter_coursevideomodel_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursevideomodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
