# Generated by Django 4.0.5 on 2022-08-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0010_alter_coursevideomodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideomodel',
            name='duration',
        ),
    ]
