# Generated by Django 4.0.5 on 2022-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_video', '0011_remove_coursevideomodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideomodel',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
