# Generated by Django 4.0.5 on 2022-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contactusmodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
