# Generated by Django 4.0.5 on 2022-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_bio_usermodel_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_image_public_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
