# Generated by Django 4.0.5 on 2022-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_profile_image_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='history',
            field=models.JSONField(default='{}', null=True),
        ),
    ]
