# Generated by Django 4.0.5 on 2022-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='history',
            field=models.JSONField(null=True),
        ),
    ]
